[tool.poetry]
name = "cpp-project-template"
version = "0.0.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "The Unlicense"
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
conan = "*"
gcovr = "*"
ninja = "*"
pre-commit = "*"
clang-format = "16.0.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
